spring.application.name=documenthub
spring.datasource.url=jdbc:mysql://localhost:3306/document_recovery_db
spring.datasource.username=root
spring.datasource.password=santhoshmysqlpwd123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port=8081

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=santhoshb1503@gmail.com
spring.mail.password=dxqapcndbqkuecpc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.user.name=admin
spring.security.user.password=admin123

logging.level.org.springframework.mail=DEBUG

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB
